name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download Release Artifact
      uses: dsaltares/fetch-gh-release-asset@1.0.0
      with:
        version: 'tags/${{ github.event.release.tag_name }}'
        file: "DemoAPI.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
      
